---
paths:
  grid_data: "/home/pietrorm/Documents/CODE/Collab_Teleriscaldamento/data/NetData419.mat"
  input_data: "/home/pietrorm/Documents/CODE/Collab_Teleriscaldamento/data/InData_interpolated.mat"
  multiple_data: "/Users/pietrorandomazzarino/Documents/DOTTORATO/CODE/Collab_Teleriscaldamento/data/"
  py_interpreter: '/home/pietrorm/Environments/District_heating/bin/python'

#scenario with dist grid replica
num_Grids: 1

#scenario with actual data decomment if using
#num_Grids: None

#properties
properties:
  cpw: 4186
  rhow: 1000
  U: 1
  T_inf: 288.1500
  branches:
    Ctube: True
    cpste: 461
    rhste: 7850 # must be multiplied
    D_ext:
      c1: 1.10025364222324
      c2: 0.005506287389632
  init:
    T_utenza_in: 353.1500
    TBC: 391.1500
    T_in_ritorno: 318.1500

#simulation
START: '2013-05-11T21:23:58.970460+07:00' #utc format or arrow getable format
END: '2013-05-11T21:23:58.970460+07:00' #utc format or arrow getable format
TS_SIZE: 60    #in seconds 300
DURATION: 2156  # 432 in number of timesteps

#aiomas
HOST: "localhost"
PORT: 5780
codec: None # dont know how to use this
