---
paths:
  grid_data: "/Users/pietrorandomazzarino/Documents/DOTTORATO/CODE/Collab_Teleriscaldamento/data/CompleteNetwork_G1_D5"
  input_data: "/Users/pietrorandomazzarino/Documents/DOTTORATO/CODE/Collab_Teleriscaldamento/data/InData_interpolated.mat"
  net_data: "/Users/pietrorandomazzarino/Documents/DOTTORATO/CODE/Collab_Teleriscaldamento/data/NetData419.mat"
  py_interpreter: '/home/pietrorm/Environments/District_heating/bin/python' # no need

# Scenario creation: **************************************
ScenarioCreation:
  from_data: False # if True should have a datafile for the whole grid
  real_net: "" # path of the real grid datafile
  sample_net: "/Users/pietrorandomazzarino/Documents/DOTTORATO/CODE/Collab_Teleriscaldamento/data/NetData419.mat"
  #numDistGrids: 5 # when creating from sample number of distribution grid randomly connected
  #numGenerators: 1 # when creating from sample number of generators in place of sample_BCT

  Transp_properties: # used to augment physical params of Transp grid from sample_grid
    len_mul : 1.2
    D_mul : 1.3

  Distributions: # key:value pairs for distribution grids with the list of nodes id of the connection to transport
    Grids:
      0: [193]
      1: [119]
      2: [81]
      3: [93]
      4: [114]



  Generators:  # key:value pairs for generators with the node id of the position
    0: 4

  Storages:     # key:value pairs for storages with the node id of the position (could be any node of the whole system)
    0: 4
    1: 4
    2: 4
    3: 'dist_0_45'
    4: 'dist_0_183'


  sto_schedule:
    1:
      charge: !!python/tuple ['0am','4am']
      discharge: !!python/tuple ['5am','7am']
    2:
      charge: !!python/tuple [ '0am','4am' ]
      discharge: !!python/tuple [ '5am','7am' ]
    3:
      charge: !!python/tuple [ '0am','4am' ]
      discharge: !!python/tuple [ '5am','7am' ]
#***********************************************************

#scenario with dist grid replica comment when using data of complete network
#num_Grids: 1

#scenario with actual data decomment if using
num_Grids: None

# Simulation process ***************************************
#properties
properties:
  cpw: 4186
  rhow: 1000
  U: 1
  T_inf: 288.1500
  branches:
    Ctube: True
    cpste: 461
    rhste: 7850 # must be multiplied
    D_ext:
      c1: 1.10025364222324
      c2: 0.005506287389632
  init: # todo change in init dist and change all over the code
    T_utenza_in: 353.1500
    TBC: 391.1500
    T_in_ritorno: 318.1500
    T_gen: 403.0000



#simulation
START: '2013-05-11T21:23:58.970460+07:00' #utc format or arrow getable format
END: '2013-05-11T21:23:58.970460+07:00' #utc format or arrow getable format
TS_SIZE: 60    #in seconds 300
DURATION: 2156 #2156  # 432 in number of timesteps

#aiomas
HOST: "localhost"
PORT: 5780
codec: None # dont know how to use this
