---
paths:
  grid_data: "/Users/pietrorandomazzarino/Documents/DOTTORATO/CODE/Collab_Teleriscaldamento/data/CompleteNetwork_G1_D5"
  input_data: "/home/pietrorm/Documents/CODE/Collab_Teleriscaldamento/data/InData_interpolated.mat"
  net_data: "/home/pietrorm/Documents/CODE/Collab_Teleriscaldamento/data/NetData419.mat"
  py_interpreter: '/home/pietrorm/Environments/District_heating/bin/python' # no need
  scenario: "/home/pietrorm/Documents/CODE/Collab_Teleriscaldamento/data/CompleteNetwork_final"

# Scenario creation: **************************************
ScenarioCreation:
  from_data: False # if True should have a datafile for the whole grid
  real_net: "" # path of the real grid datafile
  sample_net: "/home/pietrorm/Documents/CODE/Collab_Teleriscaldamento/data/NetData419.mat"
  #numDistGrids: 5 # when creating from sample number of distribution grid randomly connected
  #numGenerators: 1 # when creating from sample number of generators in place of sample_BCT

  Transp_properties: # used to augment physical params of Transp grid from sample_grid
    len_mul : 1.2
    D_mul : 10

  Distributions: # key:value pairs for distribution grids with the list of nodes id of the connection to transport
    Grids:
      0: ['transp_193']
      1: ['transp_119']
      2: ['transp_81']
      3: ['transp_93']
      4: ['transp_114']



  Generators:  # key:value pairs for generators with the node id of the position
    0: 'transp_4'

  Storages:     # key:value pairs for storages with the node id of the position (could be any node of the whole system)
    #NB se voglio mettere storages nelle BCT devo usare i nomi che avranno nella grid finale quindi gli stessi delle connessioni li sopra
    #per ora solo su rete di trasporto
    0: 'transp_202'
    1: 'transp_203'
    2: 'transp_204'

  sto_conn:
    transp_202 : 'transp_3'
    transp_203 : 'transp_12'
    transp_204 : 'transp_6'

  sto_schedule:
    transp_202:
      charge: !!python/tuple [0,4]
      discharge: !!python/tuple [6,8]
    transp_203:
      charge: !!python/tuple [0,4]
      discharge: !!python/tuple [6,8]
    transp_204:
      charge: !!python/tuple [0,4]
      discharge: !!python/tuple [6,8]

  properties:
    cpw: 4186
    rhow: 1000
    U: 1
    T_inf: 288.1500
    branches:
      Ctube: True
      cpste: 461
      rhste: 7850 # must be multiplied
      D_ext:
        c1: 1.10025364222324
        c2: 0.005506287389632
    init:
      T_utenza_in: 353.1500
      T_utenza_ret: 330.000
      TBC: 391.1500
      T_BCT_ret: 318.1500
      T_gen: 403.1500
      T_gen_ret: 300.0000
#***********************************************************

#scenario with dist grid replica comment when using data of complete network
#num_Grids: 1

#scenario with actual data decomment if using
num_Grids: None

# Simulation process ***************************************
#properties
properties:
  cpw: 4186
  rhow: 1000
  U: 1
  T_inf: 288.1500
  branches:
    Ctube: True
    cpste: 461
    rhste: 7850 # must be multiplied
    D_ext:
      c1: 1.10025364222324
      c2: 0.005506287389632
  init: # todo change in init dist and change all over the code
    T_utenza_in: 353.1500
    T_utenza_ret: 330.000
    TBC: 391.1500
    T_BCT_ret: 318.1500
    T_gen: 403.0000
    T_gen_ret: 300.0000
    T_in_ritorno: 318.1500
    T_init_transp : 400.1500

#simulation
START: '2013-05-11T12:00:00.970460' #'2013-05-11T12:00:00.970460'   #utc format or arrow getable format
END: '2013-05-11T21:23:58.970460' #utc format or arrow getable format
TS_SIZE: 60    #in seconds 300
DURATION: 2156 #2156  # 432 in number of timesteps

#aiomas
HOST: "localhost"
PORT: 5780
codec: None # dont know how to use this
